# name: Angular Web App - CI/CD

# on:
#   push:
#     branches: ["master", "feature/first-deploy-to-s3"]
#   pull_request:
#     branches: ["master"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js 18
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: "npm"
#       - name: Install npm dependencies
#         run: npm ci
#       - name: Build 
#         run: npm run build-prod
#       - name: Cache /dist for the Deploy job
#         uses: actions/upload-artifact@v3
#         with:
#           name: cached-dist
#           path: dist

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Restore cached /dist
#         uses: actions/download-artifact@v3
#         with:
#           name: cached-dist
#           path: dist


    